server:
  port: 1004
spring:
    datasource:
     driver-class-name: com.mysql.jdbc.Driver
     password: abcd
     url: jdbc:mysql://localhost:3306/harish
     username: root
    jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
    mail:
     host : smtp.gmail.com
     port : 587
     username : harishnallaballe@gmail.com
     password : mtkw mhzv wjyi derp
     properties:
       mail:
         smtp:
           auth : true
           starttls:
              enable : true
    
  